CREATE TABLE productionweaver_productions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    production_title TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    owner INTEGER NOT NULL REFERENCES productionweaver_users(id) ON DELETE CASCADE
);