CREATE TYPE exterior_interior AS ENUM (
    'EXT.',
    'INT.'
);

CREATE TYPE time_of_day AS ENUM (
    'DAY',
    'DUSK',
    'NIGHT',
    'DAWN'
);

CREATE TABLE productionweaver_scenes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    setting exterior_interior NOT NULL,
    location TEXT NOT NULL,
    time_of_day time_of_day NOT NULL,
    short_summary TEXT,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    production_id INTEGER NOT NULL REFERENCES productionweaver_productions(id) ON DELETE CASCADE,
    owner INTEGER NOT NULL REFERENCES productionweaver_users(id) ON DELETE CASCADE
);