CREATE TYPE element_category AS ENUM (
    'Animal Handler',
    'Cast',
    'Extras',
    'Greenery',
    'Livestock',
    'Makeup/Hair',
    'Mechanical FX',
    'Miscellanous',
    'Music',
    'Optical FX',
    'Props',
    'Security',
    'Set Dressing',
    'Sound',
    'Special Equipment',
    'Special FX',
    'Stunts',
    'Vehicles',
    'Visual FX',
    'Wardrobe'
);

CREATE TABLE productionweaver_elements (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category element_category NOT NULL,
    description TEXT NOT NULL,
    date_created TIMESTAMP NOT NULL DEFAULT now(),
    scene_id INTEGER NOT NULL REFERENCES productionweaver_scenes(id) ON DELETE CASCADE,
    owner INTEGER NOT NULL REFERENCES productionweaver_users(id) ON DELETE CASCADE
);